spring:
  profiles:
    active: dev

  datasource:
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: admin
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 500MB
      # 设置总上传的文件大小
      max-request-size: 2000MB

  devtools:
    add-properties: true
    livereload:
      port: 35799

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.jh.domain
  config-location: classpath:MyBatis/mybatis-config.xml


logging:
  level:
    root: info
    org.springframework: info
    com.jh: debug
    org.apache.shiro: debug
    org.springframework.web: debug
  config: classpath:log4j2/log4j2.xml

server:
  port: 80
  tomcat:
    threads:
      max: 800
      min-spare: 30
    max-connections: 8192
    max-http-form-post-size: 1024MB
    uri-encoding: utf-8

  servlet:
    context-path: /


shiro-redis:
  enabled: true
  redis-manager:
    deploy-mode: standalone
    host: 127.0.0.1:6379
  session-dao:
    expire: -2    # -1: 永不过期， -2：与session过期时间相同
    session-in-memory-timeout: 1000
    cache-manager:
      expire: 1800

shiro:
  cookie:
    cookieName: SHIROSESSIONID
  session:
    timeout: 3600



